import { db } from '../config/database';
import { labs } from './schema/labs';

/**
 * Seeds all 35 labs across 10 categories.
 * Run: npx tsx src/db/seed-labs.ts
 */
async function seedLabs() {
    console.log('Seeding 35 labs across 10 categories...\n');

    const allLabs = [
        // ═══ CATEGORY 1 — LINUX FUNDAMENTALS ═══
        {
            id: 'linux-shell-basics',
            title: 'Linux Shell Basics',
            description: 'Master essential shell commands: navigation, file operations, pipes, and redirection.',
            difficulty: 'beginner',
            category: 'linux',
            dockerImage: 'lab-linux-shell-basics:latest',
            estimatedMinutes: 30,
            ttlSeconds: 3600,
            cpuLimit: 0.25,
            memoryLimitMb: 256,
            exposePort: 7681,
            isActive: true,
            tags: ['linux', 'shell', 'beginner'],
            steps: [
                { id: 'step-1', name: 'Navigate to workspace', validation_cmd: 'test -d ~/workspace/project' },
                { id: 'step-2', name: 'List files recursively', validation_cmd: 'which tree' },
                { id: 'step-3', name: 'Find text in files', validation_cmd: 'grep -r "Hello" ~/workspace' },
            ],
            resources: [],
        },
        {
            id: 'linux-permissions',
            title: 'Linux File Permissions',
            description: 'Understand chmod, chown, SUID, SGID, sticky bits, and multi-user file access.',
            difficulty: 'beginner',
            category: 'linux',
            dockerImage: 'lab-linux-permissions:latest',
            estimatedMinutes: 30,
            ttlSeconds: 3600,
            cpuLimit: 0.25,
            memoryLimitMb: 256,
            exposePort: 7681,
            isActive: true,
            tags: ['linux', 'permissions', 'security'],
            steps: [
                { id: 'step-1', name: 'Check file permissions', validation_cmd: 'stat ~/permissions-lab/public.txt' },
                { id: 'step-2', name: 'Change permissions', validation_cmd: 'test -w ~/permissions-lab/shared' },
            ],
            resources: [],
        },
        {
            id: 'linux-processes',
            title: 'Linux Process Management',
            description: 'Learn ps, top, kill, jobs, signals, and background process management.',
            difficulty: 'intermediate',
            category: 'linux',
            dockerImage: 'lab-linux-processes:latest',
            estimatedMinutes: 30,
            ttlSeconds: 3600,
            cpuLimit: 0.5,
            memoryLimitMb: 256,
            exposePort: 7681,
            isActive: true,
            tags: ['linux', 'processes', 'sysadmin'],
            steps: [
                { id: 'step-1', name: 'Find the background process', validation_cmd: 'cat ~/background.pid' },
                { id: 'step-2', name: 'Kill the process', validation_cmd: '! ps -p $(cat ~/background.pid) > /dev/null 2>&1' },
            ],
            resources: [],
        },
        {
            id: 'linux-text-processing',
            title: 'Text Processing with grep, awk, sed',
            description: 'Process CSV files and logs using grep, awk, sed, cut, sort, uniq.',
            difficulty: 'intermediate',
            category: 'linux',
            dockerImage: 'lab-linux-text-processing:latest',
            estimatedMinutes: 45,
            ttlSeconds: 3600,
            cpuLimit: 0.25,
            memoryLimitMb: 256,
            exposePort: 7681,
            isActive: true,
            tags: ['linux', 'text', 'awk', 'sed', 'grep'],
            steps: [
                { id: 'step-1', name: 'Extract student names from CSV', validation_cmd: 'awk -F, \'$3=="student"{print $2}\' ~/data/users.csv | wc -l' },
                { id: 'step-2', name: 'Count ERROR lines in log', validation_cmd: 'grep -c ERROR ~/data/server.log' },
            ],
            resources: [],
        },

        // ═══ CATEGORY 2 — NETWORKING ═══
        {
            id: 'networking-tools',
            title: 'Networking Diagnostic Tools',
            description: 'Use ping, traceroute, dig, nslookup, netcat, nmap for network diagnostics.',
            difficulty: 'beginner',
            category: 'networking',
            dockerImage: 'lab-networking-tools:latest',
            estimatedMinutes: 30,
            ttlSeconds: 3600,
            cpuLimit: 0.25,
            memoryLimitMb: 256,
            exposePort: 7681,
            isActive: true,
            tags: ['networking', 'dns', 'diagnostics'],
            steps: [
                { id: 'step-1', name: 'Ping localhost', validation_cmd: 'ping -c 1 localhost' },
                { id: 'step-2', name: 'Check DNS', validation_cmd: 'which dig' },
            ],
            resources: [],
        },
        {
            id: 'networking-http',
            title: 'HTTP & REST Fundamentals',
            description: 'Make HTTP requests with curl, httpie. Understand methods, headers, status codes.',
            difficulty: 'beginner',
            category: 'networking',
            dockerImage: 'lab-networking-http:latest',
            estimatedMinutes: 30,
            ttlSeconds: 3600,
            cpuLimit: 0.25,
            memoryLimitMb: 256,
            exposePort: 7681,
            isActive: true,
            tags: ['networking', 'http', 'rest', 'curl'],
            steps: [
                { id: 'step-1', name: 'GET request to local server', validation_cmd: 'curl -s http://localhost:8080' },
            ],
            resources: [],
        },
        {
            id: 'networking-ssh',
            title: 'SSH Key Management',
            description: 'Generate SSH keys, manage authorized_keys, configure SSH client.',
            difficulty: 'intermediate',
            category: 'networking',
            dockerImage: 'lab-networking-ssh:latest',
            estimatedMinutes: 30,
            ttlSeconds: 3600,
            cpuLimit: 0.25,
            memoryLimitMb: 256,
            exposePort: 7681,
            isActive: true,
            tags: ['networking', 'ssh', 'security'],
            steps: [
                { id: 'step-1', name: 'Generate SSH key', validation_cmd: 'test -f ~/.ssh/lab_key' },
            ],
            resources: [],
        },

        // ═══ CATEGORY 3 — DOCKER ═══
        {
            id: 'docker-basics',
            title: 'Docker Fundamentals',
            description: 'Run containers, manage images, understand Docker lifecycle.',
            difficulty: 'beginner',
            category: 'docker',
            dockerImage: 'lab-docker-basics:latest',
            estimatedMinutes: 45,
            ttlSeconds: 3600,
            cpuLimit: 1.0,
            memoryLimitMb: 1024,
            exposePort: 7681,
            isActive: true,
            tags: ['docker', 'containers', 'beginner'],
            steps: [
                { id: 'step-1', name: 'Run hello-world', validation_cmd: 'docker images hello-world --format "{{.Repository}}"' },
                { id: 'step-2', name: 'Run alpine interactively', validation_cmd: 'docker ps -a --filter ancestor=alpine --format "{{.Status}}"' },
            ],
            resources: [],
        },
        {
            id: 'docker-build',
            title: 'Building Docker Images',
            description: 'Write Dockerfiles, build custom images, understand layers and caching.',
            difficulty: 'intermediate',
            category: 'docker',
            dockerImage: 'lab-docker-build:latest',
            estimatedMinutes: 45,
            ttlSeconds: 3600,
            cpuLimit: 1.0,
            memoryLimitMb: 1024,
            exposePort: 7681,
            isActive: true,
            tags: ['docker', 'dockerfile', 'build'],
            steps: [
                { id: 'step-1', name: 'Write a Dockerfile', validation_cmd: 'test -f ~/sample-app/Dockerfile' },
                { id: 'step-2', name: 'Build the image', validation_cmd: 'docker images my-app --format "{{.Repository}}"' },
            ],
            resources: [],
        },
        {
            id: 'docker-compose-lab',
            title: 'Docker Compose Multi-Service',
            description: 'Define multi-container apps with docker-compose, volumes, and networks.',
            difficulty: 'intermediate',
            category: 'docker',
            dockerImage: 'lab-docker-compose-lab:latest',
            estimatedMinutes: 45,
            ttlSeconds: 3600,
            cpuLimit: 1.0,
            memoryLimitMb: 1024,
            exposePort: 7681,
            isActive: true,
            tags: ['docker', 'compose', 'multi-service'],
            steps: [
                { id: 'step-1', name: 'Complete docker-compose.yml', validation_cmd: 'test -f ~/compose-exercise/docker-compose.yml' },
            ],
            resources: [],
        },
        {
            id: 'docker-networking-lab',
            title: 'Docker Networking',
            description: 'Create custom networks, connect containers, inspect network config.',
            difficulty: 'intermediate',
            category: 'docker',
            dockerImage: 'lab-docker-networking-lab:latest',
            estimatedMinutes: 30,
            ttlSeconds: 3600,
            cpuLimit: 1.0,
            memoryLimitMb: 1024,
            exposePort: 7681,
            isActive: true,
            tags: ['docker', 'networking', 'bridge'],
            steps: [
                { id: 'step-1', name: 'Create lab-net network', validation_cmd: 'docker network inspect lab-net' },
            ],
            resources: [],
        },

        // ═══ CATEGORY 4 — KUBERNETES ═══
        {
            id: 'k8s-kubectl-basics',
            title: 'kubectl Essentials',
            description: 'Navigate a Kubernetes cluster with kubectl: get, describe, logs, exec.',
            difficulty: 'beginner',
            category: 'kubernetes',
            dockerImage: 'lab-k8s-kubectl-basics:latest',
            estimatedMinutes: 45,
            ttlSeconds: 3600,
            cpuLimit: 1.0,
            memoryLimitMb: 1024,
            exposePort: 7681,
            isActive: true,
            tags: ['k8s', 'kubectl', 'beginner'],
            steps: [
                { id: 'step-1', name: 'Get cluster nodes', validation_cmd: 'kubectl get nodes' },
                { id: 'step-2', name: 'List all namespaces', validation_cmd: 'kubectl get namespaces' },
            ],
            resources: [],
        },
        {
            id: 'k8s-deployments',
            title: 'Kubernetes Deployments',
            description: 'Create, scale, update, and rollback Deployments.',
            difficulty: 'intermediate',
            category: 'kubernetes',
            dockerImage: 'lab-k8s-deployments:latest',
            estimatedMinutes: 45,
            ttlSeconds: 3600,
            cpuLimit: 1.0,
            memoryLimitMb: 1024,
            exposePort: 7681,
            isActive: true,
            tags: ['k8s', 'deployments', 'rolling-update'],
            steps: [
                { id: 'step-1', name: 'Apply deployment', validation_cmd: 'kubectl get deployment nginx-deployment' },
                { id: 'step-2', name: 'Scale to 3 replicas', validation_cmd: 'kubectl get deployment nginx-deployment -o jsonpath="{.spec.replicas}" | grep 3' },
            ],
            resources: [],
        },
        {
            id: 'k8s-services',
            title: 'Kubernetes Services',
            description: 'Expose workloads with ClusterIP, NodePort, and LoadBalancer services.',
            difficulty: 'intermediate',
            category: 'kubernetes',
            dockerImage: 'lab-k8s-services:latest',
            estimatedMinutes: 45,
            ttlSeconds: 3600,
            cpuLimit: 1.0,
            memoryLimitMb: 1024,
            exposePort: 7681,
            isActive: true,
            tags: ['k8s', 'services', 'networking'],
            steps: [
                { id: 'step-1', name: 'Expose with ClusterIP', validation_cmd: 'kubectl get svc web' },
            ],
            resources: [],
        },
        {
            id: 'k8s-configmaps-secrets',
            title: 'ConfigMaps & Secrets',
            description: 'Manage configuration and secrets in Kubernetes pods.',
            difficulty: 'intermediate',
            category: 'kubernetes',
            dockerImage: 'lab-k8s-configmaps-secrets:latest',
            estimatedMinutes: 45,
            ttlSeconds: 3600,
            cpuLimit: 1.0,
            memoryLimitMb: 1024,
            exposePort: 7681,
            isActive: true,
            tags: ['k8s', 'configmap', 'secrets'],
            steps: [
                { id: 'step-1', name: 'Create ConfigMap', validation_cmd: 'kubectl get configmap' },
                { id: 'step-2', name: 'Create Secret', validation_cmd: 'kubectl get secret' },
            ],
            resources: [],
        },

        // ═══ CATEGORY 5 — DATABASES ═══
        {
            id: 'db-postgres-basics',
            title: 'PostgreSQL Fundamentals',
            description: 'Write SQL queries: SELECT, JOIN, INSERT, UPDATE, indexes, and aggregations.',
            difficulty: 'beginner',
            category: 'databases',
            dockerImage: 'lab-db-postgres-basics:latest',
            estimatedMinutes: 45,
            ttlSeconds: 3600,
            cpuLimit: 0.5,
            memoryLimitMb: 512,
            exposePort: 7681,
            isActive: true,
            tags: ['database', 'postgresql', 'sql'],
            steps: [
                { id: 'step-1', name: 'Connect to database', validation_cmd: 'psql -U labuser -d labdb -c "SELECT 1"' },
                { id: 'step-2', name: 'Query employees', validation_cmd: 'psql -U labuser -d labdb -c "SELECT count(*) FROM employees"' },
            ],
            resources: [],
        },
        {
            id: 'db-redis-basics',
            title: 'Redis Data Structures',
            description: 'Work with strings, hashes, lists, sets, sorted sets, and TTL.',
            difficulty: 'beginner',
            category: 'databases',
            dockerImage: 'lab-db-redis-basics:latest',
            estimatedMinutes: 30,
            ttlSeconds: 3600,
            cpuLimit: 0.25,
            memoryLimitMb: 256,
            exposePort: 7681,
            isActive: true,
            tags: ['database', 'redis', 'nosql'],
            steps: [
                { id: 'step-1', name: 'PING Redis', validation_cmd: 'redis-cli PING' },
                { id: 'step-2', name: 'Get leaderboard', validation_cmd: 'redis-cli ZRANGEBYSCORE leaderboard 0 100' },
            ],
            resources: [],
        },
        {
            id: 'db-mysql-basics',
            title: 'MySQL Fundamentals',
            description: 'Create tables, write queries, manage users, and optimize with indexes.',
            difficulty: 'beginner',
            category: 'databases',
            dockerImage: 'lab-db-mysql-basics:latest',
            estimatedMinutes: 45,
            ttlSeconds: 3600,
            cpuLimit: 0.5,
            memoryLimitMb: 512,
            exposePort: 7681,
            isActive: true,
            tags: ['database', 'mysql', 'sql'],
            steps: [
                { id: 'step-1', name: 'Connect to MySQL', validation_cmd: 'mysql -u labuser -plabpass shopdb -e "SELECT 1"' },
            ],
            resources: [],
        },
        {
            id: 'db-mongodb-basics',
            title: 'MongoDB Document Operations',
            description: 'CRUD with documents, queries, aggregation pipeline, and indexes.',
            difficulty: 'intermediate',
            category: 'databases',
            dockerImage: 'lab-db-mongodb-basics:latest',
            estimatedMinutes: 45,
            ttlSeconds: 3600,
            cpuLimit: 0.5,
            memoryLimitMb: 512,
            exposePort: 7681,
            isActive: true,
            tags: ['database', 'mongodb', 'nosql'],
            steps: [
                { id: 'step-1', name: 'Connect to MongoDB', validation_cmd: 'mongosh --quiet --eval "db.stats()"' },
            ],
            resources: [],
        },

        // ═══ CATEGORY 6 — CI/CD ═══
        {
            id: 'cicd-git-workflows',
            title: 'Git Branching & Merging',
            description: 'Practice branching, merging, conflict resolution, rebasing, and tagging.',
            difficulty: 'beginner',
            category: 'cicd',
            dockerImage: 'lab-cicd-git-workflows:latest',
            estimatedMinutes: 30,
            ttlSeconds: 3600,
            cpuLimit: 0.25,
            memoryLimitMb: 256,
            exposePort: 7681,
            isActive: true,
            tags: ['git', 'branching', 'merge'],
            steps: [
                { id: 'step-1', name: 'Merge feature branch', validation_cmd: 'cd ~/git-lab && git log --oneline | grep "Add login"' },
            ],
            resources: [],
        },
        {
            id: 'cicd-github-actions',
            title: 'GitHub Actions CI Pipeline',
            description: 'Write a GitHub Actions workflow with build, test, and deploy stages.',
            difficulty: 'intermediate',
            category: 'cicd',
            dockerImage: 'lab-cicd-github-actions:latest',
            estimatedMinutes: 30,
            ttlSeconds: 3600,
            cpuLimit: 0.25,
            memoryLimitMb: 256,
            exposePort: 7681,
            isActive: true,
            tags: ['cicd', 'github-actions', 'yaml'],
            steps: [
                { id: 'step-1', name: 'Complete CI workflow', validation_cmd: 'cat ~/my-project/.github/workflows/ci.yml | grep pytest' },
            ],
            resources: [],
        },
        {
            id: 'cicd-docker-pipeline',
            title: 'Docker Build Pipeline',
            description: 'Build, test, and deploy containerized apps in a CI pipeline.',
            difficulty: 'intermediate',
            category: 'cicd',
            dockerImage: 'lab-cicd-docker-pipeline:latest',
            estimatedMinutes: 30,
            ttlSeconds: 3600,
            cpuLimit: 1.0,
            memoryLimitMb: 1024,
            exposePort: 7681,
            isActive: true,
            tags: ['cicd', 'docker', 'pipeline'],
            steps: [
                { id: 'step-1', name: 'Build and run app', validation_cmd: 'docker images my-pipeline-app' },
            ],
            resources: [],
        },
        {
            id: 'cicd-jenkins-basics',
            title: 'Jenkins Pipeline (Jenkinsfile)',
            description: 'Write declarative Jenkinsfiles with build, test, and deploy stages.',
            difficulty: 'intermediate',
            category: 'cicd',
            dockerImage: 'lab-cicd-jenkins-basics:latest',
            estimatedMinutes: 30,
            ttlSeconds: 3600,
            cpuLimit: 0.25,
            memoryLimitMb: 256,
            exposePort: 7681,
            isActive: true,
            tags: ['cicd', 'jenkins', 'pipeline'],
            steps: [
                { id: 'step-1', name: 'Complete Jenkinsfile', validation_cmd: 'grep -c "stage" ~/jenkins-lab/Jenkinsfile' },
            ],
            resources: [],
        },

        // ═══ CATEGORY 7 — IaC ═══
        {
            id: 'iac-terraform-basics',
            title: 'Terraform Basics',
            description: 'Write HCL, init/plan/apply with the local provider — no cloud account needed.',
            difficulty: 'beginner',
            category: 'iac',
            dockerImage: 'lab-iac-terraform-basics:latest',
            estimatedMinutes: 45,
            ttlSeconds: 3600,
            cpuLimit: 0.5,
            memoryLimitMb: 512,
            exposePort: 7681,
            isActive: true,
            tags: ['iac', 'terraform', 'hcl'],
            steps: [
                { id: 'step-1', name: 'Init Terraform', validation_cmd: 'test -d ~/exercises/.terraform' },
                { id: 'step-2', name: 'Apply config', validation_cmd: 'test -f ~/exercises/hello.txt' },
            ],
            resources: [],
        },
        {
            id: 'iac-terraform-modules',
            title: 'Terraform Modules',
            description: 'Create reusable Terraform modules with variables, outputs, and composition.',
            difficulty: 'intermediate',
            category: 'iac',
            dockerImage: 'lab-iac-terraform-modules:latest',
            estimatedMinutes: 45,
            ttlSeconds: 3600,
            cpuLimit: 0.5,
            memoryLimitMb: 512,
            exposePort: 7681,
            isActive: true,
            tags: ['iac', 'terraform', 'modules'],
            steps: [
                { id: 'step-1', name: 'Call module twice', validation_cmd: 'grep -c "module" ~/exercises/main.tf' },
            ],
            resources: [],
        },
        {
            id: 'iac-ansible-basics',
            title: 'Ansible Playbooks',
            description: 'Write and run Ansible playbooks with tasks, handlers, and variables.',
            difficulty: 'intermediate',
            category: 'iac',
            dockerImage: 'lab-iac-ansible-basics:latest',
            estimatedMinutes: 45,
            ttlSeconds: 3600,
            cpuLimit: 0.5,
            memoryLimitMb: 512,
            exposePort: 7681,
            isActive: true,
            tags: ['iac', 'ansible', 'automation'],
            steps: [
                { id: 'step-1', name: 'Run playbook', validation_cmd: 'test -d /tmp/ansible-output' },
            ],
            resources: [],
        },
        {
            id: 'iac-localstack-aws',
            title: 'AWS with LocalStack',
            description: 'Practice AWS CLI commands (S3, SQS, DynamoDB) against a local stack.',
            difficulty: 'advanced',
            category: 'iac',
            dockerImage: 'lab-iac-localstack-aws:latest',
            estimatedMinutes: 60,
            ttlSeconds: 7200,
            cpuLimit: 1.0,
            memoryLimitMb: 1024,
            exposePort: 7681,
            isActive: true,
            tags: ['iac', 'aws', 'localstack', 'cloud'],
            steps: [
                { id: 'step-1', name: 'Create S3 bucket', validation_cmd: 'aws --endpoint-url http://localhost:4566 s3 ls' },
            ],
            resources: [],
        },

        // ═══ CATEGORY 8 — OBSERVABILITY ═══
        {
            id: 'obs-prometheus-basics',
            title: 'Prometheus Monitoring',
            description: 'Query metrics with PromQL, configure scrape targets, and set up alerts.',
            difficulty: 'intermediate',
            category: 'observability',
            dockerImage: 'lab-obs-prometheus-basics:latest',
            estimatedMinutes: 45,
            ttlSeconds: 3600,
            cpuLimit: 0.5,
            memoryLimitMb: 512,
            exposePort: 7681,
            isActive: true,
            tags: ['monitoring', 'prometheus', 'promql'],
            steps: [
                { id: 'step-1', name: 'Query Prometheus', validation_cmd: 'curl -s http://localhost:9090/api/v1/query?query=up' },
            ],
            resources: [],
        },
        {
            id: 'obs-log-analysis',
            title: 'Log Analysis & Parsing',
            description: 'Parse, filter, and analyze application logs with grep, awk, and jq.',
            difficulty: 'beginner',
            category: 'observability',
            dockerImage: 'lab-obs-log-analysis:latest',
            estimatedMinutes: 30,
            ttlSeconds: 3600,
            cpuLimit: 0.25,
            memoryLimitMb: 256,
            exposePort: 7681,
            isActive: true,
            tags: ['observability', 'logs', 'analysis'],
            steps: [
                { id: 'step-1', name: 'Count error lines', validation_cmd: 'grep -c ERROR ~/logs/app.log' },
            ],
            resources: [],
        },
        {
            id: 'obs-healthchecks',
            title: 'Health Checks & Liveness Probes',
            description: 'Implement and test /health and /ready endpoints for your services.',
            difficulty: 'beginner',
            category: 'observability',
            dockerImage: 'lab-obs-healthchecks:latest',
            estimatedMinutes: 30,
            ttlSeconds: 3600,
            cpuLimit: 0.25,
            memoryLimitMb: 256,
            exposePort: 7681,
            isActive: true,
            tags: ['observability', 'healthcheck', 'liveness'],
            steps: [
                { id: 'step-1', name: 'Check /health endpoint', validation_cmd: 'curl -s http://localhost:8080/health | grep ok' },
            ],
            resources: [],
        },

        // ═══ CATEGORY 9 — SECURITY ═══
        {
            id: 'security-tls-basics',
            title: 'TLS & Certificate Management',
            description: 'Generate self-signed certs, inspect certificates, and understand the TLS handshake.',
            difficulty: 'beginner',
            category: 'security',
            dockerImage: 'lab-security-tls-basics:latest',
            estimatedMinutes: 30,
            ttlSeconds: 3600,
            cpuLimit: 0.25,
            memoryLimitMb: 256,
            exposePort: 7681,
            isActive: true,
            tags: ['security', 'tls', 'certificates'],
            steps: [
                { id: 'step-1', name: 'Generate self-signed cert', validation_cmd: 'test -f ~/tls-lab/cert.pem' },
            ],
            resources: [],
        },
        {
            id: 'security-linux-hardening',
            title: 'Linux Security Hardening',
            description: 'Find misconfigurations, manage firewall rules, audit SUID binaries.',
            difficulty: 'intermediate',
            category: 'security',
            dockerImage: 'lab-security-linux-hardening:latest',
            estimatedMinutes: 45,
            ttlSeconds: 3600,
            cpuLimit: 0.5,
            memoryLimitMb: 512,
            exposePort: 7681,
            isActive: true,
            tags: ['security', 'hardening', 'audit'],
            steps: [
                { id: 'step-1', name: 'Find world-writable files', validation_cmd: 'find / -perm -o+w -type f 2>/dev/null | head -1' },
            ],
            resources: [],
        },
        {
            id: 'security-secrets-vault',
            title: 'HashiCorp Vault Secrets',
            description: 'Store, retrieve, and manage secrets with Vault KV engine.',
            difficulty: 'intermediate',
            category: 'security',
            dockerImage: 'lab-security-secrets-vault:latest',
            estimatedMinutes: 45,
            ttlSeconds: 3600,
            cpuLimit: 0.5,
            memoryLimitMb: 512,
            exposePort: 7681,
            isActive: true,
            tags: ['security', 'vault', 'secrets'],
            steps: [
                { id: 'step-1', name: 'Read a secret', validation_cmd: 'VAULT_ADDR=http://127.0.0.1:8200 VAULT_TOKEN=root vault kv get secret/myapp' },
            ],
            resources: [],
        },
        {
            id: 'security-container-scanning',
            title: 'Container Image Scanning with Trivy',
            description: 'Scan Docker images for CVEs and misconfigurations with Trivy.',
            difficulty: 'intermediate',
            category: 'security',
            dockerImage: 'lab-security-container-scanning:latest',
            estimatedMinutes: 30,
            ttlSeconds: 3600,
            cpuLimit: 1.0,
            memoryLimitMb: 1024,
            exposePort: 7681,
            isActive: true,
            tags: ['security', 'scanning', 'trivy', 'docker'],
            steps: [
                { id: 'step-1', name: 'Scan alpine image', validation_cmd: 'trivy image --severity HIGH alpine:latest 2>&1 | head -1' },
            ],
            resources: [],
        },

        // ═══ CATEGORY 10 — PYTHON FOR DEVOPS ═══
        {
            id: 'python-automation',
            title: 'Python Automation Scripts',
            description: 'Write Python scripts for file operations, API calls, and data processing.',
            difficulty: 'beginner',
            category: 'python',
            dockerImage: 'lab-python-automation:latest',
            estimatedMinutes: 45,
            ttlSeconds: 3600,
            cpuLimit: 0.25,
            memoryLimitMb: 256,
            exposePort: 7681,
            isActive: true,
            tags: ['python', 'automation', 'scripting'],
            steps: [
                { id: 'step-1', name: 'Complete exercise 1', validation_cmd: 'python3 ~/exercises/exercise1.py && test -f ~/exercises/output.txt' },
            ],
            resources: [],
        },
        {
            id: 'python-cli-tools',
            title: 'Build CLI Tools with Click',
            description: 'Create command-line tools using Python Click with arguments, options, and groups.',
            difficulty: 'intermediate',
            category: 'python',
            dockerImage: 'lab-python-cli-tools:latest',
            estimatedMinutes: 45,
            ttlSeconds: 3600,
            cpuLimit: 0.25,
            memoryLimitMb: 256,
            exposePort: 7681,
            isActive: true,
            tags: ['python', 'cli', 'click'],
            steps: [
                { id: 'step-1', name: 'Implement greet command', validation_cmd: 'python3 ~/exercises/cli_tool.py greet --name Test' },
            ],
            resources: [],
        },
        {
            id: 'python-yaml-json',
            title: 'YAML & JSON Processing',
            description: 'Parse, transform, and generate YAML/JSON config files with Python.',
            difficulty: 'beginner',
            category: 'python',
            dockerImage: 'lab-python-yaml-json:latest',
            estimatedMinutes: 30,
            ttlSeconds: 3600,
            cpuLimit: 0.25,
            memoryLimitMb: 256,
            exposePort: 7681,
            isActive: true,
            tags: ['python', 'yaml', 'json', 'config'],
            steps: [
                { id: 'step-1', name: 'Parse YAML config', validation_cmd: 'python3 -c "import yaml; print(yaml.safe_load(open(\'exercises/config.yaml\'))[\'app\'][\'version\'])"' },
            ],
            resources: [],
        },
        {
            id: 'python-devops-scripts',
            title: 'System Monitoring with Python',
            description: 'Build monitoring scripts with psutil: CPU, memory, disk, and alerting.',
            difficulty: 'intermediate',
            category: 'python',
            dockerImage: 'lab-python-devops-scripts:latest',
            estimatedMinutes: 45,
            ttlSeconds: 3600,
            cpuLimit: 0.25,
            memoryLimitMb: 256,
            exposePort: 7681,
            isActive: true,
            tags: ['python', 'monitoring', 'psutil', 'devops'],
            steps: [
                { id: 'step-1', name: 'Run monitor script', validation_cmd: 'python3 -c "import psutil; print(psutil.cpu_percent())"' },
            ],
            resources: [],
        },
    ];

    await db.insert(labs).values(allLabs).onConflictDoNothing();

    console.log(`✅ Seeded ${allLabs.length} labs across ${new Set(allLabs.map(l => l.category)).size} categories`);
    console.log('\nCategories:');
    const cats = [...new Set(allLabs.map(l => l.category))];
    for (const cat of cats) {
        const count = allLabs.filter(l => l.category === cat).length;
        console.log(`  ${cat}: ${count} labs`);
    }

    process.exit(0);
}

seedLabs().catch((err) => {
    console.error('Seed error:', err);
    process.exit(1);
});
